### ISSUE TITLE
iTunes connect error missing NSPhotoLibraryUsageDescription key

### ISSUE THREAD

**Issue by RoelandSalij** [mendix/CameraWidgetForPhoneGap#12]
https://forum.mendixcloud.com/link/questions/86003

**Comment by simo101** [comment]
This is probably something that can't be changed in the widget. It needs to be changed in the config.xml. So probably not a widget issue, but a Mendix phonegap build pack issue.

**Comment by KevinVlaanderen** [comment]
A fix for this is in the works; it will be released and available on the publish tab soon

**Comment by Andries-Smit** [comment]
Issue is resolved with new release of the Mendix "Publish App for Mobile App Stores"

For older version that dont want to upgrade, the `config.xml` could be updates with the settings, see for a sample in the standard config.xml delived by mendix.

``` xml
<plugin name="cordova-plugin-camera" source="npm" spec="2.4.0">
	<param name="CAMERA_USAGE_DESCRIPTION" value="This app needs to access your camera" />
	<param name="PHOTOLIBRARY_USAGE_DESCRIPTION" value="This app needs to access your photo library" />
</plugin>
```
