### ISSUE TITLE
Show progress when uploading

### ISSUE THREAD

**Issue by MulderWH** [mendix/CameraWidgetForPhoneGap#23]
Given the top smartphone snappers around, when you take a photo, then it takes some time to upload your picture to the Mendix database. 

It would be nice if the widget shows the default spinner when uploading, so you know it's busy processing your image. I have alrady added the show progress in [this](https://github.com/MulderWH/CameraWidgetForPhoneGap/tree/show-progress) branch, but there's a bug in it:(

The bug is that the spinner keeps spinning, when you click cancel in the camera pop over. Anyways it would be nice if the camera widget supports a spinner when uploading.

**Comment by sjeefr** [comment]
@Andries-Smit And we are three updates further and it's not available?

**Comment by Andries-Smit** [comment]
The progress was no longer possible in the same way.
We implemented in a new way you can set "Block during upload" with a progress message. Almost as good as.... though no real way to cancel the transaction on a slow connection.

Available now in the app store version 4.0
Cheers,
Andries
