### ISSUE TITLE
This line should be changed from google maps

### ISSUE THREAD

**Issue by simo101** [mendix/CameraWidgetForPhoneGap#27]
This line currently references google maps. When it should be the camera widget.
[https://github.com/mendix/CameraWidgetForPhoneGap/blob/master/src/CameraWidgetForPhoneGap/CameraWidgetForPhoneGap.webmodeler.js#L30](https://github.com/mendix/CameraWidgetForPhoneGap/blob/master/src/CameraWidgetForPhoneGap/CameraWidgetForPhoneGap.webmodeler.js#L30)

**Comment by Andries-Smit** [comment]
indeed, we already have PR #25 on this. we release soon

**Comment by Andries-Smit** [comment]
Release
