### ISSUE TITLE
Responsive Camera Widget

### ISSUE THREAD

**Issue by mjrennie** [mendix/CameraWidgetForPhoneGap#28]
The ability for the camera widget to only be available in native mobile and be able to upload an image file in responsive web. It is currently possible to hide the widget on the web but it then appears upon changing the browser window size and doesn't allow interaction in the web.

**Comment by simo101** [comment]
We should be able to use it regardless of being on a device or not. The only widget that can do this currently is the file upload functionality. However this widget is horrendous to style. Rather than using phonegap capabilities we could use html 5 camera option?

**Comment by Andries-Smit** [comment]
We are not planning to make this widget available for web. Though i seen that some parters posted a web camera widget base on HTM5 https://appstore.home.mendix.com/link/app/107943/
