### ISSUE TITLE
Unable to detect camera

### ISSUE THREAD

**Issue by sjeefr** [mendix/CameraWidgetForPhoneGap#31]
A common thing, but I haven't find a solution to make this widget work on my iPhone, except by using the Mendix app to access my app. When reaching out via the browser and going to the app URL, the app says "Unable to detect camera". Pretty large impediment if you ask me..

**Comment by Andries-Smit** [comment]
Dear Sander,

Please note this camera feature is implemented for phone gap apps only. I you wish to use this camera widget you have to wrap the app. https://docs.mendix.com/refguide/developing-hybrid-mobile-apps

Camera access on the web is not available. However there is a widget in development, however it is not released, so API and implementation is till subject to change, and even not might not be released all or loos supported in future version. If you accept that disclaimer you can have a look at:
https://github.com/FlockOfBirds/camera/releases/tag/v1.0.0-Beta

Cheers, Andries

**Comment by Andries-Smit** [comment]
Widget not indent to work this way. Will close the issue.

**Comment by Kwame10** [comment]
Hi everyone, I have try the camera widget and it works in phone gap but not not the web. Is there another widget or new developed widget that works  for web? Thanks
