### ISSUE TITLE
Camera widget constructor errors because of _GetOptions() function

### ISSUE THREAD

**Issue by davelina** [mendix/CameraWidgetForPhoneGap#35]
Hi, 

This widget worked and works in all modern browsers, but for IE when run in Mx7 (7.19). 
The reason for this is the _GetOptions(); part in the code instead of the _GetOptions: function();

Result in the browser is that all widget can't be constructed, resulting in a lot of red error messages (when you use a lot of widgets). 

Replace the code and all problems are solved.

**Comment by Andries-Smit** [comment]
Hi Dave

Thank you for reporting this issue. I could reproduce, and fix it.

Though please note; that this widget is intended for Cordova PhoneGap Apps. There is no browser support for actual using the camera.

Cheers, Andries

**Comment by Andries-Smit** [comment]
We created a fix. Please let us know if this solves your issue. 
https://github.com/FlockOfBirds/CameraWidgetForPhoneGap/releases/tag/v4.0.1-beta
Cheers, Andries

**Comment by davelina** [comment]
That seems to do the trick  ;) 

Thanks for the quick response and action!

**Comment by Andries-Smit** [comment]
Published version 4.0.1 into the app store https://appstore.home.mendix.com/link/app/1377/
